const dataUpload = {
  "Faculty of Engineering": {
    "Computer Science and Engineering": {
      "Semester 1": [],
      "Semester 2": [],
      "Semester 3": [],
      "Semester 4": [],
      "Semester 5": [],
      "Semester 6": [],
      "Semester 7": [],
      "Semester 8": [],
    },
    "Electronics and Communication Engineering": {
      "Semester 1": [],
      "Semester 2": [],
      "Semester 3": [],
      "Semester 4": [],
      "Semester 5": [],
      "Semester 6": [],
      "Semester 7": [],
      "Semester 8": [],
    },
    "Civil Engineering": {
      "Semester 1": [],
      "Semester 2": [],
      "Semester 3": [],
      "Semester 4": [],
      "Semester 5": [],
      "Semester 6": [],
      "Semester 7": [],
      "Semester 8": [],
    },
    "Mechanical Engineering": {
      "Semester 1": [],
      "Semester 2": [],
      "Semester 3": [],
      "Semester 4": [],
      "Semester 5": [],
      "Semester 6": [],
      "Semester 7": [],
      "Semester 8": [],
    },
    "Electrical Engineering": {
      "Semester 1": [],
      "Semester 2": [],
      "Semester 3": [],
      "Semester 4": [],
      "Semester 5": [],
      "Semester 6": [],
      "Semester 7": [],
      "Semester 8": [],
    },
    Biotechnology: {
      "Semester 1": [],
      "Semester 2": [],
      "Semester 3": [],
      "Semester 4": [],
      "Semester 5": [],
      "Semester 6": [],
      "Semester 7": [],
      "Semester 8": [],
    },
  },
  "Faculty of Science": {
    Physics: {
      "Semester 1": [],
      "Semester 2": [],
      "Semester 3": [],
      "Semester 4": [],
      "Semester 5": [],
      "Semester 6": [],
      "Semester 7": [],
      "Semester 8": [],
    },
    Chemistry: {
      "Semester 1": [],
      "Semester 2": [],
      "Semester 3": [],
      "Semester 4": [],
      "Semester 5": [],
      "Semester 6": [],
      "Semester 7": [],
      "Semester 8": [],
      "Semester 9": [],
      "Semester 10": [],
    },
    Mathematics: {
      "Semester 1": [],
      "Semester 2": [],
      "Semester 3": [],
      "Semester 4": [],
      "Semester 5": [],
      "Semester 6": [],
      "Semester 7": [],
      "Semester 8": [],
      "Semester 9": [],
      "Semester 10": [],
    },
  },
  "Faculty of Management": {
    "Bachelor of Business Administration": {
      "Semester 1": [],
      "Semester 2": [],
      "Semester 3": [],
      "Semester 4": [],
      "Semester 5": [],
      "Semester 6": [],
      "Semester 7": [],
      "Semester 8": [],
    },
    "Master of Business Administration": {
      "Semester 1": [],
      "Semester 2": [],
      "Semester 3": [],
      "Semester 4": [],
    },
  },
};
export default dataUpload;
